/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Sign in with email and password. Returns a bearer token (send it as
         *     ``Authorization: Bearer <token>``).
         */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change your own password (current password required); ends your other sessions.
         */
        post: operations["change_password_v1_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Answer from retrieved passages only; abstains (with matched cases) when it cannot.
         */
        post: operations["chat_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description The same answer as ``/v1/chat``, streamed: progress stages and the passages sent to the
         *     model while it works, then the answer. Errors after the stream has started arrive as an
         *     ``error`` event with the JSON route's codes. Closing the connection cancels the answer
         *     (an in-flight model call is aborted and recorded as cancelled).
         */
        post: operations["chat_stream_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/courts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Courts
         * @description Courts with eligible judgments (for search filters).
         */
        get: operations["read_courts_v1_courts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/judgments/{judgment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Judgment */
        get: operations["read_judgment_v1_judgments__judgment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/passages/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Passage
         * @description A passage of an eligible judgment with its neighbours, for reading in context.
         */
        get: operations["read_passage_v1_passages__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/judgments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Judgment
         * @description Find a case by citation or name, to add a gold case search did not return.
         */
        get: operations["find_judgment_v1_review_judgments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_v1_review_questions_get"];
        put?: never;
        /** Create Question */
        post: operations["create_question_v1_review_questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Question */
        get: operations["read_question_v1_review_questions__question_id__get"];
        /** Update Question */
        put: operations["update_question_v1_review_questions__question_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/questions/{question_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Mark the labels as lawyer-reviewed (gold cases, or an expected abstention, required).
         */
        post: operations["approve_v1_review_questions__question_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/questions/{question_id}/preview-answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Answer
         * @description What the system answers today (the normal pipeline; audited for the reviewer).
         */
        post: operations["preview_answer_v1_review_questions__question_id__preview_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/questions/{question_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen */
        post: operations["reopen_v1_review_questions__question_id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/questions/{question_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire */
        post: operations["retire_v1_review_questions__question_id__retire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Judgments */
        post: operations["search_judgments_v1_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CaseResult
         * @description One case; ``judgments`` lists every URI publishing the same text.
         */
        CaseResult: {
            /** Also Published As */
            also_published_as: components["schemas"]["JudgmentRef"][];
            judgment: components["schemas"]["JudgmentRef"];
            /**
             * Match Type
             * @enum {string}
             */
            match_type: "citation" | "case_name" | "lexical" | "dense" | "hybrid";
            /** Passages */
            passages: components["schemas"]["PassageResult"][];
            /** Score */
            score: number;
        };
        /** ChatAnswerEvent */
        ChatAnswerEvent: {
            answer: components["schemas"]["ChatResponse"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "answer";
        };
        /** ChatClaim */
        ChatClaim: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "holding" | "obiter" | "fact" | "inference";
            /**
             * Pinpoint
             * @description Verified PDF page(s) of the passage holding the quote (1-based), else null
             */
            pinpoint: string | null;
            /**
             * Quote
             * @description Verbatim from the passage quote_chunk_id (checked)
             */
            quote: string;
            /**
             * Quote Chunk Id
             * Format: uuid
             */
            quote_chunk_id: string;
            /** Source Numbers */
            source_numbers: number[];
            /**
             * Support Score
             * @description Probability that a cited passage entails the claim (NLI model)
             */
            support_score: number | null;
            /** Text */
            text: string;
        };
        /** ChatErrorEvent */
        ChatErrorEvent: {
            error: components["schemas"]["ErrorBody"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
        };
        /** ChatPassage */
        ChatPassage: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Excerpt */
            excerpt: string;
            /** Page End */
            page_end: number | null;
            /**
             * Page Reference Status
             * @enum {string}
             */
            page_reference_status: "verified" | "unknown" | "pending";
            /**
             * Page Start
             * @description 0-based PDF page; only when verified
             */
            page_start: number | null;
        };
        /** ChatRequest */
        ChatRequest: {
            filters?: components["schemas"]["SearchFilters"];
            /** Question */
            question: string;
            /** Session Id */
            session_id?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Abstain Reason */
            abstain_reason: ("no_results" | "model_abstained" | "no_supported_claims" | "invalid_model_output") | null;
            /** Abstained */
            abstained: boolean;
            /**
             * Answer
             * @description Built from verified claims only; [n] = sources[n]
             */
            answer: string | null;
            /**
             * Attribution
             * @default Source: Ghana Legal Information Institute (GhaLII, ghalii.org), licensed CC BY-NC 4.0. Non-commercial use with attribution.
             */
            attribution: string;
            /** Claims */
            claims: components["schemas"]["ChatClaim"][];
            generation: components["schemas"]["GenerationInfo"] | null;
            /** Limitations */
            limitations: string[];
            /** Matched Cases */
            matched_cases: components["schemas"]["JudgmentRef"][];
            /** Model Limitations */
            model_limitations: string | null;
            /**
             * Notice
             * @default Assisted legal research, not legal advice. Corpus coverage may be incomplete; absence of a result does not mean absence in Ghanaian law.
             */
            notice: string;
            query_info: components["schemas"]["QueryInfo"];
            /** Question */
            question: string;
            /** Session Id */
            session_id: string | null;
            /** Sources */
            sources: components["schemas"]["ChatSource"][];
        };
        /**
         * ChatSource
         * @description A judgment cited by the answer; ``number`` is its marker in the answer text.
         */
        ChatSource: {
            /** Also Published As */
            also_published_as: components["schemas"]["JudgmentRef"][];
            judgment: components["schemas"]["JudgmentRef"];
            /** Number */
            number: number;
            /** Passages */
            passages: components["schemas"]["ChatPassage"][];
        };
        /**
         * ChatSourcesEvent
         * @description The passages sent to the model, in envelope order (before it answers).
         */
        ChatSourcesEvent: {
            /** Passages */
            passages: components["schemas"]["PassageResult"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sources";
        };
        /**
         * ChatStageEvent
         * @description Progress of a streamed answer: retrieving, the model writing, claims being checked.
         */
        ChatStageEvent: {
            /**
             * Claims
             * @description Statements being checked (checking)
             */
            claims?: number | null;
            /**
             * Stage
             * @enum {string}
             */
            stage: "searching" | "drafting" | "checking";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stage";
        };
        /**
         * ChatStreamEventDoc
         * @description One server-sent event of ``POST /v1/chat/stream`` (its ``data`` line, as JSON).
         */
        ChatStreamEventDoc: components["schemas"]["ChatStageEvent"] | components["schemas"]["ChatSourcesEvent"] | components["schemas"]["ChatAnswerEvent"] | components["schemas"]["ChatErrorEvent"];
        /** ContextPassage */
        ContextPassage: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Excerpt */
            excerpt: string;
            /** Ordinal */
            ordinal: number;
            /** Page End */
            page_end: number | null;
            /**
             * Page Reference Status
             * @enum {string}
             */
            page_reference_status: "verified" | "unknown" | "pending";
            /**
             * Page Start
             * @description 0-based PDF page; only when verified
             */
            page_start: number | null;
            /** Section Label */
            section_label: string | null;
        };
        /** CourtInfo */
        CourtInfo: {
            /** Court Code */
            court_code: string;
            /** Court Name */
            court_name: string | null;
            /** Judgments */
            judgments: number;
        };
        /** CourtsResponse */
        CourtsResponse: {
            /** Courts */
            courts: components["schemas"]["CourtInfo"][];
        };
        /** Created */
        Created: {
            /** Id */
            id: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            }[] | null;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** GenerationInfo */
        GenerationInfo: {
            /** Input Tokens */
            input_tokens: number;
            /** Invalid Source Ids */
            invalid_source_ids: number;
            /** Latency Ms */
            latency_ms: number;
            /**
             * Model
             * @description The model the provider reports having run
             */
            model: string;
            /** Output Tokens */
            output_tokens: number;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /**
             * Removed Claims
             * @description Claims dropped by verification, by reason
             */
            removed_claims: {
                [key: string]: number;
            };
            /**
             * Requested Model
             * @description The configured model name (may be an alias)
             */
            requested_model: string;
            /** Source Ids Cited */
            source_ids_cited: number;
            /** Sources Sent */
            sources_sent: number;
            /**
             * Support Model
             * @description NLI model@revision that checked the claims
             */
            support_model: string;
        };
        /**
         * GoldAction
         * @enum {string}
         */
        GoldAction: "created" | "imported" | "edited" | "approved" | "reopened" | "retired";
        /**
         * GoldDraft
         * @description What a reviewer edits.
         */
        GoldDraft: {
            /**
             * Category
             * @enum {string}
             */
            category: "citation" | "case_name" | "issue" | "fact_pattern" | "out_of_corpus";
            /**
             * Expect No Answer
             * @default false
             */
            expect_no_answer: boolean;
            filters?: components["schemas"]["SearchFilters"];
            /** Gold Canonical Uris */
            gold_canonical_uris?: string[];
            /** Gold Passages */
            gold_passages?: components["schemas"]["GoldPassage"][];
            /** Notes */
            notes?: string | null;
            /** Question */
            question: string;
        };
        /**
         * GoldPassage
         * @description A passage that answers the question, as verbatim text of one of the gold judgments
         *     (text, not a chunk id: it survives re-chunking).
         */
        GoldPassage: {
            /** Canonical Uri */
            canonical_uri: string;
            /** Text */
            text: string;
        };
        /**
         * GoldStatus
         * @enum {string}
         */
        GoldStatus: "draft" | "approved" | "retired";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryEntry */
        HistoryEntry: {
            action: components["schemas"]["GoldAction"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** User */
            user: string | null;
        };
        /** JudgmentDetail */
        JudgmentDetail: {
            /**
             * Attribution
             * @default Source: Ghana Legal Information Institute (GhaLII, ghalii.org), licensed CC BY-NC 4.0. Non-commercial use with attribution.
             */
            attribution: string;
            /** Case Number */
            case_number: string | null;
            /** Chunk Count */
            chunk_count: number;
            /** Judges */
            judges: string[];
            judgment: components["schemas"]["JudgmentRef"];
            /** Language */
            language: string | null;
            /** Neutral Citation */
            neutral_citation: string | null;
            /**
             * Notice
             * @default Assisted legal research, not legal advice. Corpus coverage may be incomplete; absence of a result does not mean absence in Ghanaian law.
             */
            notice: string;
            /** Source Status */
            source_status: string;
            /** Sources */
            sources: components["schemas"]["SourceInfo"][];
        };
        /** JudgmentRef */
        JudgmentRef: {
            /** Canonical Uri */
            canonical_uri: string;
            /** Citation */
            citation: string;
            /** Court Code */
            court_code: string | null;
            /** Court Name */
            court_name: string | null;
            /** Judgment Date */
            judgment_date: string | null;
            /**
             * Judgment Id
             * Format: uuid
             */
            judgment_id: string;
            /** Jurisdiction */
            jurisdiction: string | null;
            /** Source Url */
            source_url: string;
            /** Title */
            title: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /**
             * Expires At
             * Format: date-time
             * @description Absolute expiry (idle sessions end sooner)
             */
            expires_at: string;
            /**
             * Token
             * @description Bearer token; store it HttpOnly and send it on each request
             */
            token: string;
            user: components["schemas"]["UserInfo"];
        };
        /**
         * PassageContext
         * @description A passage with the passages around it in the same judgment, for reading in context.
         */
        PassageContext: {
            /** After */
            after: components["schemas"]["ContextPassage"][];
            /**
             * Attribution
             * @default Source: Ghana Legal Information Institute (GhaLII, ghalii.org), licensed CC BY-NC 4.0. Non-commercial use with attribution.
             */
            attribution: string;
            /** Before */
            before: components["schemas"]["ContextPassage"][];
            judgment: components["schemas"]["JudgmentRef"];
            /**
             * Notice
             * @default Assisted legal research, not legal advice. Corpus coverage may be incomplete; absence of a result does not mean absence in Ghanaian law.
             */
            notice: string;
            passage: components["schemas"]["ContextPassage"];
        };
        /** PassageResult */
        PassageResult: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Dense Score
             * @description Cosine similarity
             */
            dense_score?: number | null;
            /** Excerpt */
            excerpt: string;
            judgment: components["schemas"]["JudgmentRef"];
            /** Lexical Score */
            lexical_score?: number | null;
            /**
             * Match Type
             * @enum {string}
             */
            match_type: "citation" | "case_name" | "lexical" | "dense" | "hybrid";
            /** Page End */
            page_end: number | null;
            /**
             * Page Reference Status
             * @enum {string}
             */
            page_reference_status: "verified" | "unknown" | "pending";
            /**
             * Page Start
             * @description Set only when page_reference_status=verified
             */
            page_start: number | null;
            /** Paragraph Refs */
            paragraph_refs: string[];
            /** Rerank Score */
            rerank_score?: number | null;
            /** Rrf Score */
            rrf_score?: number | null;
            /** Section Label */
            section_label: string | null;
        };
        /** PasswordChangeRequest */
        PasswordChangeRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** QueryInfo */
        QueryInfo: {
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Degraded Reason */
            degraded_reason?: string | null;
            /** Detected Citation */
            detected_citation: string | null;
            /** Filters Applied */
            filters_applied: {
                [key: string]: string | number;
            };
            /** Looks Like Case Name */
            looks_like_case_name: boolean;
            /**
             * Mode Requested
             * @default hybrid
             * @enum {string}
             */
            mode_requested: "hybrid" | "lexical" | "dense";
            /**
             * Mode Used
             * @default hybrid
             * @enum {string}
             */
            mode_used: "hybrid" | "lexical" | "dense";
            /**
             * Reranked
             * @default false
             */
            reranked: boolean;
        };
        /** ReviewCounts */
        ReviewCounts: {
            /** Approved By Category */
            approved_by_category: {
                [key: string]: number;
            };
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            target: components["schemas"]["ReviewTarget"];
        };
        /** ReviewDetail */
        ReviewDetail: {
            /** @description What search returns now (with the filters) */
            candidates: components["schemas"]["SearchResponse"];
            /**
             * Gold Cases
             * @description The gold cases that are eligible judgments (a URI missing here is not)
             */
            gold_cases: components["schemas"]["JudgmentRef"][];
            /** History */
            history: components["schemas"]["HistoryEntry"][];
            question: components["schemas"]["ReviewQuestion"];
        };
        /** ReviewList */
        ReviewList: {
            counts: components["schemas"]["ReviewCounts"];
            /** Questions */
            questions: components["schemas"]["ReviewSummary"][];
        };
        /** ReviewQuestion */
        ReviewQuestion: {
            /**
             * Category
             * @enum {string}
             */
            category: "citation" | "case_name" | "issue" | "fact_pattern" | "out_of_corpus";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expect No Answer */
            expect_no_answer: boolean;
            /** Filters */
            filters: {
                [key: string]: unknown;
            };
            /** Gold Canonical Uris */
            gold_canonical_uris: string[];
            /** Gold Passages */
            gold_passages: components["schemas"]["GoldPassage"][];
            /** Id */
            id: string;
            /** Notes */
            notes: string | null;
            /** Question */
            question: string;
            /** Reviewed At */
            reviewed_at: string | null;
            /**
             * Reviewed By
             * @description Reviewer's display name
             */
            reviewed_by: string | null;
            status: components["schemas"]["GoldStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** ReviewSummary */
        ReviewSummary: {
            /**
             * Category
             * @enum {string}
             */
            category: "citation" | "case_name" | "issue" | "fact_pattern" | "out_of_corpus";
            /** Gold Cases */
            gold_cases: number;
            /** Gold Passages */
            gold_passages: number;
            /** Id */
            id: string;
            /** Question */
            question: string;
            status: components["schemas"]["GoldStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ReviewTarget */
        ReviewTarget: {
            /** Max */
            max: number;
            /** Min */
            min: number;
        };
        /** ReviewWrite */
        ReviewWrite: {
            /**
             * Category
             * @enum {string}
             */
            category: "citation" | "case_name" | "issue" | "fact_pattern" | "out_of_corpus";
            /**
             * Expect No Answer
             * @default false
             */
            expect_no_answer: boolean;
            filters?: components["schemas"]["SearchFilters"];
            /** Gold Canonical Uris */
            gold_canonical_uris?: string[];
            /** Gold Passages */
            gold_passages?: components["schemas"]["GoldPassage"][];
            /** Notes */
            notes?: string | null;
            /** Question */
            question: string;
            /** Version */
            version: number;
        };
        /**
         * SearchFilters
         * @description Strict filters: applied exactly, never widened.
         */
        SearchFilters: {
            /**
             * Court
             * @description AKN court code
             */
            court?: string | null;
            /** Judge */
            judge?: string | null;
            /**
             * Jurisdiction
             * @description AKN code
             */
            jurisdiction?: string | null;
            /** Year From */
            year_from?: number | null;
            /** Year To */
            year_to?: number | null;
        };
        /** SearchRequest */
        SearchRequest: {
            filters?: components["schemas"]["SearchFilters"];
            /**
             * Mode
             * @default hybrid
             * @enum {string}
             */
            mode: "hybrid" | "lexical" | "dense";
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /** Query */
            query: string;
            /**
             * Rerank
             * @default true
             */
            rerank: boolean;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /**
             * Attribution
             * @default Source: Ghana Legal Information Institute (GhaLII, ghalii.org), licensed CC BY-NC 4.0. Non-commercial use with attribution.
             */
            attribution: string;
            /** Cases */
            cases: components["schemas"]["CaseResult"][];
            /**
             * Notice
             * @default Assisted legal research, not legal advice. Corpus coverage may be incomplete; absence of a result does not mean absence in Ghanaian law.
             */
            notice: string;
            /** Passages */
            passages: components["schemas"]["PassageResult"][];
            /** Query */
            query: string;
            query_info: components["schemas"]["QueryInfo"];
        };
        /** SourceInfo */
        SourceInfo: {
            /** Kind */
            kind: string;
            /** Mime Type */
            mime_type: string | null;
            /** Original Url */
            original_url: string | null;
            /** Rights Status */
            rights_status: string;
            /** Verification Status */
            verification_status: string;
        };
        /** UserInfo */
        UserInfo: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "researcher" | "reviewer";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionBody */
        VersionBody: {
            /** Version */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    change_password_v1_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chat_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chat_stream_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Server-sent events, in order: stage and sources events, then exactly one answer or error event. The schema describes one event's data line (JSON); the event name equals its type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_courts_v1_courts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourtsResponse"];
                };
            };
        };
    };
    read_judgment_v1_judgments__judgment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                judgment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JudgmentDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_passage_v1_passages__chunk_id__get: {
        parameters: {
            query?: {
                /** @description Neighbouring passages per side */
                context?: number;
            };
            header?: never;
            path: {
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PassageContext"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_judgment_v1_review_judgments_get: {
        parameters: {
            query: {
                citation: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_questions_v1_review_questions_get: {
        parameters: {
            query?: {
                status?: string | null;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_question_v1_review_questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoldDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Created"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_question_v1_review_questions__question_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_question_v1_review_questions__question_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    approve_v1_review_questions__question_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preview_answer_v1_review_questions__question_id__preview_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reopen_v1_review_questions__question_id__reopen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    retire_v1_review_questions__question_id__retire_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_judgments_v1_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
